import type { CoachPlanResponse } from "@/types/plan";

/**
 * Formats a Date as a floating ICS datetime string: YYYYMMDDTHHMMSS
 * "Floating" means no Z suffix — calendar apps interpret it in the user's local timezone.
 * We use this because the scheduler produces times relative to the user's local clock
 * (8am–10pm local) and we never collect an explicit IANA timezone.
 */
function formatIcsDate(date: Date): string {
  const pad = (n: number, len = 2) => String(n).padStart(len, "0");
  return (
    `${date.getFullYear()}${pad(date.getMonth() + 1)}${pad(date.getDate())}` +
    `T${pad(date.getHours())}${pad(date.getMinutes())}${pad(date.getSeconds())}`
  );
}

/**
 * Formats a Date as a UTC ICS datetime string: YYYYMMDDTHHMMSSz
 * Used only for DTSTAMP (file-creation timestamp), which must be UTC per RFC 5545.
 */
function formatIcsDateUtc(date: Date): string {
  const pad = (n: number, len = 2) => String(n).padStart(len, "0");
  return (
    `${date.getUTCFullYear()}${pad(date.getUTCMonth() + 1)}${pad(date.getUTCDate())}` +
    `T${pad(date.getUTCHours())}${pad(date.getUTCMinutes())}${pad(date.getUTCSeconds())}Z`
  );
}

/**
 * Escapes special characters in ICS text fields per RFC 5545:
 * backslash, semicolon, comma, and newlines must be escaped.
 */
function escapeIcsText(text: string): string {
  return text
    .replace(/\\/g, "\\\\")
    .replace(/;/g, "\\;")
    .replace(/,/g, "\\,")
    .replace(/\n/g, "\\n")
    .replace(/\r/g, "");
}

/**
 * Folds long ICS lines at 75 octets per RFC 5545 §3.1.
 * Continuation lines begin with a single space.
 */
function foldLine(line: string): string {
  if (line.length <= 75) return line;
  const chunks: string[] = [];
  chunks.push(line.slice(0, 75));
  let i = 75;
  while (i < line.length) {
    chunks.push(" " + line.slice(i, i + 74));
    i += 74;
  }
  return chunks.join("\r\n");
}

/**
 * Converts a CoachPlanResponse into a valid .ics (iCalendar) string.
 * Each ScheduledBlock in the daily schedule becomes one VEVENT.
 */
export function buildIcsString(plan: CoachPlanResponse): string {
  const now = new Date();
  const dtstamp = formatIcsDateUtc(now);
  const lines: string[] = [];

  lines.push("BEGIN:VCALENDAR");
  lines.push("VERSION:2.0");
  lines.push("PRODID:-//Comeback Coach//EN");
  lines.push("CALSCALE:GREGORIAN");
  lines.push("METHOD:PUBLISH");
  lines.push("X-WR-CALNAME:Comeback Study Plan");
  lines.push(`X-WR-CALDESC:${escapeIcsText(plan.summary)}`);

  let eventIndex = 0;

  for (const day of plan.dailySchedule) {
    for (const block of day.blocks) {
      let startDate: Date;
      let endDate: Date;

      try {
        startDate = new Date(block.start);
        endDate = new Date(block.end);
        if (isNaN(startDate.getTime()) || isNaN(endDate.getTime())) continue;
      } catch {
        continue;
      }

      const summary = block.chunkLabel
        ? `${escapeIcsText(block.taskTitle)} — ${escapeIcsText(block.chunkLabel)}`
        : escapeIcsText(block.taskTitle);

      const uid = `${day.date}-${block.taskId}-${eventIndex}@comeback-coach`;

      lines.push("BEGIN:VEVENT");
      lines.push(`UID:${uid}`);
      lines.push(`DTSTAMP:${dtstamp}`);
      lines.push(`DTSTART:${formatIcsDate(startDate)}`);
      lines.push(`DTEND:${formatIcsDate(endDate)}`);
      lines.push(foldLine(`SUMMARY:${summary}`));
      lines.push(
        foldLine(
          `DESCRIPTION:Study session generated by Comeback Coach. Task: ${escapeIcsText(block.taskTitle)}`,
        ),
      );
      lines.push("END:VEVENT");

      eventIndex++;
    }
  }

  lines.push("END:VCALENDAR");

  // RFC 5545 requires CRLF line endings
  return lines.map(foldLine).join("\r\n");
}

/**
 * Counts the total number of scheduled blocks across all days.
 * Used by the UI to disable the export button when the schedule is empty.
 */
export function countScheduledBlocks(plan: CoachPlanResponse): number {
  return plan.dailySchedule.reduce((sum, day) => sum + day.blocks.length, 0);
}
